# Generated by Django 3.2 on 2022-08-12 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('subject', models.CharField(choices=[('li', 'Literature'), ('hi', 'History'), ('ma', 'Mathematics'), ('ph', 'physics'), ('sc', 'science fiction'), ('fi', 'philosophy'), ('dr', 'drama')], max_length=2)),
                ('language', models.CharField(choices=[('sp', 'spanish'), ('en', 'emglish'), ('fr', 'french'), ('it', 'italian'), ('jp', 'japanese')], max_length=2)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location_identifier', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('due_date', models.PositiveSmallIntegerField(default=5, verbose_name='Number of days the book will be borrowed')),
                ('is_borrowed', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('actual_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.rack')),
            ],
        ),
    ]
