# Generated by Django 3.2 on 2022-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='number',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('sp', 'Spanish'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('jp', 'Japanese')], max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('li', 'Literature'), ('hi', 'History'), ('ma', 'Mathematics'), ('ph', 'Physics'), ('sc', 'Science Fiction'), ('fi', 'Philosophy'), ('dr', 'Drama')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rack',
            name='location_identifier',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
